#!/bin/bash
echo  "Updating izing, please wait."
git checkout master
git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
#npx sequelize db:seed
pm2 restart all
cd ..
cd frontend
npm install
quasar build -P -m pwa

echo  "Update finished. Enjoy!"
